### ISSUE TITLE
Fitting Nested Effects 

### ISSUE THREAD

**Issue by Mp939199** [jendelman/StageWise#1]
I am trying to fit a model for Multiple Lattice model with Replications and Blocks Nested within the Lattice, the present syntax shown in the Vignettes "effects <- data.frame(name=c("block","stand.count"),
                      fixed=c(FALSE,TRUE),
                      factor=c(TRUE,FALSE))" doesnot allow for the to fit Nested Effects, Is there a way to include them similar to the syntax in the Asreml package
" lat + lat:rep + lat:rep:blk " ?

**Comment by jendelman** [comment]
Hello, the package does not recognize implicit nesting. You will need to explicitly nest the factors by renaming them.

**Comment by jendelman** [comment]
To clarify, effects are by default implicitly nested within environment in Stage1 because each environment is analyzed independently. Within an environment, explicit nesting is required.
